[package]
name = "rs-raft"
version = "0.1.0"
authors = ["Kanstantsin Gerasimovich <gerask@amazon.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
